run:
  modules-download-mode: readonly
linters:
  enable:
    - revive
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
